package com.xxxsarutahikoxxx.kotlin.MTGData.Type

import com.xxxsarutahikoxxx.kotlin.MTGData.Structure.*


private val _Tenth_Edition : CardSetType = CardSetTypes(listOf("Tenth Edition", "10E"))
private val _Unlimited_Edition : CardSetType = CardSetTypes(listOf("Unlimited Edition", "2ED"))
private val _Revised_Edition : CardSetType = CardSetTypes(listOf("Revised Edition", "3ED"))
private val _Fourth_Edition_Foreign_Black_Border : CardSetType = CardSetTypes(listOf("Fourth Edition Foreign Black Border", "4BB"))
private val _Fourth_Edition : CardSetType = CardSetTypes(listOf("Fourth Edition", "4ED"))
private val _Fifth_Dawn : CardSetType = CardSetTypes(listOf("Fifth Dawn", "5DN"))
private val _Fifth_Edition : CardSetType = CardSetTypes(listOf("Fifth Edition", "5ED"))
private val _Classic_Sixth_Edition : CardSetType = CardSetTypes(listOf("Classic Sixth Edition", "6ED"))
private val _Seventh_Edition : CardSetType = CardSetTypes(listOf("Seventh Edition", "7ED"))
private val _Eighth_Edition : CardSetType = CardSetTypes(listOf("Eighth Edition", "8ED"))
private val _Ninth_Edition : CardSetType = CardSetTypes(listOf("Ninth Edition", "9ED"))
private val _Aether_Revolt : CardSetType = CardSetTypes(listOf("Aether Revolt", "AER"))
private val _Amonkhet : CardSetType = CardSetTypes(listOf("Amonkhet", "AKH"))
private val _Shards_of_Alara : CardSetType = CardSetTypes(listOf("Shards of Alara", "ALA"))
private val _Alliances : CardSetType = CardSetTypes(listOf("Alliances", "ALL"))
private val _Apocalypse : CardSetType = CardSetTypes(listOf("Apocalypse", "APC"))
private val _Alara_Reborn : CardSetType = CardSetTypes(listOf("Alara Reborn", "ARB"))
private val _Arabian_Nights : CardSetType = CardSetTypes(listOf("Arabian Nights", "ARN"))
private val _Antiquities : CardSetType = CardSetTypes(listOf("Antiquities", "ATQ"))
private val _Avacyn_Restored : CardSetType = CardSetTypes(listOf("Avacyn Restored", "AVR"))
private val _Battle_for_Zendikar : CardSetType = CardSetTypes(listOf("Battle for Zendikar", "BFZ"))
private val _Born_of_the_Gods : CardSetType = CardSetTypes(listOf("Born of the Gods", "BNG"))
private val _Betrayers_of_Kamigawa : CardSetType = CardSetTypes(listOf("Betrayers of Kamigawa", "BOK"))
private val _Champions_of_Kamigawa : CardSetType = CardSetTypes(listOf("Champions of Kamigawa", "CHK"))
private val _Conflux : CardSetType = CardSetTypes(listOf("Conflux", "CON"))
private val _Coldsnap : CardSetType = CardSetTypes(listOf("Coldsnap", "CSP"))
private val _Dragons_Maze : CardSetType = CardSetTypes(listOf("Dragon's Maze", "DGM"))
private val _Dissension : CardSetType = CardSetTypes(listOf("Dissension", "DIS"))
private val _Dark_Ascension : CardSetType = CardSetTypes(listOf("Dark Ascension", "DKA"))
private val _Dominaria : CardSetType = CardSetTypes(listOf("Dominaria", "DOM"))
private val _The_Dark : CardSetType = CardSetTypes(listOf("The Dark", "DRK"))
private val _Darksteel : CardSetType = CardSetTypes(listOf("Darksteel", "DST"))
private val _Dragons_of_Tarkir : CardSetType = CardSetTypes(listOf("Dragons of Tarkir", "DTK"))
private val _Throne_of_Eldraine : CardSetType = CardSetTypes(listOf("Throne of Eldraine", "ELD"))
private val _Eldritch_Moon : CardSetType = CardSetTypes(listOf("Eldritch Moon", "EMN"))
private val _Eventide : CardSetType = CardSetTypes(listOf("Eventide", "EVE"))
private val _Exodus : CardSetType = CardSetTypes(listOf("Exodus", "EXO"))
private val _Foreign_Black_Border : CardSetType = CardSetTypes(listOf("Foreign Black Border", "FBB"))
private val _Fallen_Empires : CardSetType = CardSetTypes(listOf("Fallen Empires", "FEM"))
private val _Fate_Reforged : CardSetType = CardSetTypes(listOf("Fate Reforged", "FRF"))
private val _Future_Sight : CardSetType = CardSetTypes(listOf("Future Sight", "FUT"))
private val _Guildpact : CardSetType = CardSetTypes(listOf("Guildpact", "GPT"))
private val _Guilds_of_Ravnica : CardSetType = CardSetTypes(listOf("Guilds of Ravnica", "GRN"))
private val _Gatecrash : CardSetType = CardSetTypes(listOf("Gatecrash", "GTC"))
private val _Homelands : CardSetType = CardSetTypes(listOf("Homelands", "HML"))
private val _Hour_of_Devastation : CardSetType = CardSetTypes(listOf("Hour of Devastation", "HOU"))
private val _Ice_Age : CardSetType = CardSetTypes(listOf("Ice Age", "ICE"))
private val _Ikoria_Lair_of_Behemoths : CardSetType = CardSetTypes(listOf("Ikoria: Lair of Behemoths", "IKO"))
private val _Invasion : CardSetType = CardSetTypes(listOf("Invasion", "INV"))
private val _Innistrad : CardSetType = CardSetTypes(listOf("Innistrad", "ISD"))
private val _Journey_into_Nyx : CardSetType = CardSetTypes(listOf("Journey into Nyx", "JOU"))
private val _Judgment : CardSetType = CardSetTypes(listOf("Judgment", "JUD"))
private val _Kaladesh : CardSetType = CardSetTypes(listOf("Kaladesh", "KLD"))
private val _Khans_of_Tarkir : CardSetType = CardSetTypes(listOf("Khans of Tarkir", "KTK"))
private val _Limited_Edition_Alpha : CardSetType = CardSetTypes(listOf("Limited Edition Alpha", "LEA"))
private val _Limited_Edition_Beta : CardSetType = CardSetTypes(listOf("Limited Edition Beta", "LEB"))
private val _Legends : CardSetType = CardSetTypes(listOf("Legends", "LEG"))
private val _Legions : CardSetType = CardSetTypes(listOf("Legions", "LGN"))
private val _Lorwyn : CardSetType = CardSetTypes(listOf("Lorwyn", "LRW"))
private val _Magic_2010 : CardSetType = CardSetTypes(listOf("Magic 2010", "M10"))
private val _Magic_2011 : CardSetType = CardSetTypes(listOf("Magic 2011", "M11"))
private val _Magic_2012 : CardSetType = CardSetTypes(listOf("Magic 2012", "M12"))
private val _Magic_2013 : CardSetType = CardSetTypes(listOf("Magic 2013", "M13"))
private val _Magic_2014 : CardSetType = CardSetTypes(listOf("Magic 2014", "M14"))
private val _Magic_2015 : CardSetType = CardSetTypes(listOf("Magic 2015", "M15"))
private val _Core_Set_2019 : CardSetType = CardSetTypes(listOf("Core Set 2019", "M19"))
private val _Core_Set_2020 : CardSetType = CardSetTypes(listOf("Core Set 2020", "M20"))
private val _Core_Set_2021 : CardSetType = CardSetTypes(listOf("Core Set 2021", "M21"))
private val _Mirrodin_Besieged : CardSetType = CardSetTypes(listOf("Mirrodin Besieged", "MBS"))
private val _Mirage : CardSetType = CardSetTypes(listOf("Mirage", "MIR"))
private val _Mercadian_Masques : CardSetType = CardSetTypes(listOf("Mercadian Masques", "MMQ"))
private val _Morningtide : CardSetType = CardSetTypes(listOf("Morningtide", "MOR"))
private val _Mirrodin : CardSetType = CardSetTypes(listOf("Mirrodin", "MRD"))
private val _Nemesis : CardSetType = CardSetTypes(listOf("Nemesis", "NEM"))
private val _New_Phyrexia : CardSetType = CardSetTypes(listOf("New Phyrexia", "NPH"))
private val _Odyssey : CardSetType = CardSetTypes(listOf("Odyssey", "ODY"))
private val _Oath_of_the_Gatewatch : CardSetType = CardSetTypes(listOf("Oath of the Gatewatch", "OGW"))
private val _Onslaught : CardSetType = CardSetTypes(listOf("Onslaught", "ONS"))
private val _Magic_Origins : CardSetType = CardSetTypes(listOf("Magic Origins", "ORI"))
private val _Prophecy : CardSetType = CardSetTypes(listOf("Prophecy", "PCY"))
private val _Planar_Chaos : CardSetType = CardSetTypes(listOf("Planar Chaos", "PLC"))
private val _Planeshift : CardSetType = CardSetTypes(listOf("Planeshift", "PLS"))
private val _Ravnica_City_of_Guilds : CardSetType = CardSetTypes(listOf("Ravnica: City of Guilds", "RAV"))
private val _Rivals_of_Ixalan : CardSetType = CardSetTypes(listOf("Rivals of Ixalan", "RIX"))
private val _Ravnica_Allegiance : CardSetType = CardSetTypes(listOf("Ravnica Allegiance", "RNA"))
private val _Rise_of_the_Eldrazi : CardSetType = CardSetTypes(listOf("Rise of the Eldrazi", "ROE"))
private val _Return_to_Ravnica : CardSetType = CardSetTypes(listOf("Return to Ravnica", "RTR"))
private val _Scourge : CardSetType = CardSetTypes(listOf("Scourge", "SCG"))
private val _Shadowmoor : CardSetType = CardSetTypes(listOf("Shadowmoor", "SHM"))
private val _Shadows_over_Innistrad : CardSetType = CardSetTypes(listOf("Shadows over Innistrad", "SOI"))
private val _Saviors_of_Kamigawa : CardSetType = CardSetTypes(listOf("Saviors of Kamigawa", "SOK"))
private val _Scars_of_Mirrodin : CardSetType = CardSetTypes(listOf("Scars of Mirrodin", "SOM"))
private val _Stronghold : CardSetType = CardSetTypes(listOf("Stronghold", "STH"))
private val _Summer_Magic__Edgar : CardSetType = CardSetTypes(listOf("Summer Magic / Edgar", "SUM"))
private val _Theros_Beyond_Death : CardSetType = CardSetTypes(listOf("Theros Beyond Death", "THB"))
private val _Theros : CardSetType = CardSetTypes(listOf("Theros", "THS"))
private val _Tempest : CardSetType = CardSetTypes(listOf("Tempest", "TMP"))
private val _Torment : CardSetType = CardSetTypes(listOf("Torment", "TOR"))
private val _Time_Spiral_Timeshifted : CardSetType = CardSetTypes(listOf("Time Spiral Timeshifted", "TSB"))
private val _Time_Spiral : CardSetType = CardSetTypes(listOf("Time Spiral", "TSP"))
private val _Urzas_Destiny : CardSetType = CardSetTypes(listOf("Urza's Destiny", "UDS"))
private val _Urzas_Legacy : CardSetType = CardSetTypes(listOf("Urza's Legacy", "ULG"))
private val _Urzas_Saga : CardSetType = CardSetTypes(listOf("Urza's Saga", "USG"))
private val _Visions : CardSetType = CardSetTypes(listOf("Visions", "VIS"))
private val _War_of_the_Spark : CardSetType = CardSetTypes(listOf("War of the Spark", "WAR"))
private val _Weatherlight : CardSetType = CardSetTypes(listOf("Weatherlight", "WTH"))
private val _Worldwake : CardSetType = CardSetTypes(listOf("Worldwake", "WWK"))
private val _Ixalan : CardSetType = CardSetTypes(listOf("Ixalan", "XLN"))
private val _Zendikar : CardSetType = CardSetTypes(listOf("Zendikar", "ZEN"))
private val _Zendikar_Rising : CardSetType = CardSetTypes(listOf("Zendikar Rising", "ZNR"))

val CardSetTypes.Companion.Tenth_Edition : CardSetType get() = _Tenth_Edition
val CardSetTypes.Companion.Unlimited_Edition : CardSetType get() = _Unlimited_Edition
val CardSetTypes.Companion.Revised_Edition : CardSetType get() = _Revised_Edition
val CardSetTypes.Companion.Fourth_Edition_Foreign_Black_Border : CardSetType get() = _Fourth_Edition_Foreign_Black_Border
val CardSetTypes.Companion.Fourth_Edition : CardSetType get() = _Fourth_Edition
val CardSetTypes.Companion.Fifth_Dawn : CardSetType get() = _Fifth_Dawn
val CardSetTypes.Companion.Fifth_Edition : CardSetType get() = _Fifth_Edition
val CardSetTypes.Companion.Classic_Sixth_Edition : CardSetType get() = _Classic_Sixth_Edition
val CardSetTypes.Companion.Seventh_Edition : CardSetType get() = _Seventh_Edition
val CardSetTypes.Companion.Eighth_Edition : CardSetType get() = _Eighth_Edition
val CardSetTypes.Companion.Ninth_Edition : CardSetType get() = _Ninth_Edition
val CardSetTypes.Companion.Aether_Revolt : CardSetType get() = _Aether_Revolt
val CardSetTypes.Companion.Amonkhet : CardSetType get() = _Amonkhet
val CardSetTypes.Companion.Shards_of_Alara : CardSetType get() = _Shards_of_Alara
val CardSetTypes.Companion.Alliances : CardSetType get() = _Alliances
val CardSetTypes.Companion.Apocalypse : CardSetType get() = _Apocalypse
val CardSetTypes.Companion.Alara_Reborn : CardSetType get() = _Alara_Reborn
val CardSetTypes.Companion.Arabian_Nights : CardSetType get() = _Arabian_Nights
val CardSetTypes.Companion.Antiquities : CardSetType get() = _Antiquities
val CardSetTypes.Companion.Avacyn_Restored : CardSetType get() = _Avacyn_Restored
val CardSetTypes.Companion.Battle_for_Zendikar : CardSetType get() = _Battle_for_Zendikar
val CardSetTypes.Companion.Born_of_the_Gods : CardSetType get() = _Born_of_the_Gods
val CardSetTypes.Companion.Betrayers_of_Kamigawa : CardSetType get() = _Betrayers_of_Kamigawa
val CardSetTypes.Companion.Champions_of_Kamigawa : CardSetType get() = _Champions_of_Kamigawa
val CardSetTypes.Companion.Conflux : CardSetType get() = _Conflux
val CardSetTypes.Companion.Coldsnap : CardSetType get() = _Coldsnap
val CardSetTypes.Companion.Dragons_Maze : CardSetType get() = _Dragons_Maze
val CardSetTypes.Companion.Dissension : CardSetType get() = _Dissension
val CardSetTypes.Companion.Dark_Ascension : CardSetType get() = _Dark_Ascension
val CardSetTypes.Companion.Dominaria : CardSetType get() = _Dominaria
val CardSetTypes.Companion.The_Dark : CardSetType get() = _The_Dark
val CardSetTypes.Companion.Darksteel : CardSetType get() = _Darksteel
val CardSetTypes.Companion.Dragons_of_Tarkir : CardSetType get() = _Dragons_of_Tarkir
val CardSetTypes.Companion.Throne_of_Eldraine : CardSetType get() = _Throne_of_Eldraine
val CardSetTypes.Companion.Eldritch_Moon : CardSetType get() = _Eldritch_Moon
val CardSetTypes.Companion.Eventide : CardSetType get() = _Eventide
val CardSetTypes.Companion.Exodus : CardSetType get() = _Exodus
val CardSetTypes.Companion.Foreign_Black_Border : CardSetType get() = _Foreign_Black_Border
val CardSetTypes.Companion.Fallen_Empires : CardSetType get() = _Fallen_Empires
val CardSetTypes.Companion.Fate_Reforged : CardSetType get() = _Fate_Reforged
val CardSetTypes.Companion.Future_Sight : CardSetType get() = _Future_Sight
val CardSetTypes.Companion.Guildpact : CardSetType get() = _Guildpact
val CardSetTypes.Companion.Guilds_of_Ravnica : CardSetType get() = _Guilds_of_Ravnica
val CardSetTypes.Companion.Gatecrash : CardSetType get() = _Gatecrash
val CardSetTypes.Companion.Homelands : CardSetType get() = _Homelands
val CardSetTypes.Companion.Hour_of_Devastation : CardSetType get() = _Hour_of_Devastation
val CardSetTypes.Companion.Ice_Age : CardSetType get() = _Ice_Age
val CardSetTypes.Companion.Ikoria_Lair_of_Behemoths : CardSetType get() = _Ikoria_Lair_of_Behemoths
val CardSetTypes.Companion.Invasion : CardSetType get() = _Invasion
val CardSetTypes.Companion.Innistrad : CardSetType get() = _Innistrad
val CardSetTypes.Companion.Journey_into_Nyx : CardSetType get() = _Journey_into_Nyx
val CardSetTypes.Companion.Judgment : CardSetType get() = _Judgment
val CardSetTypes.Companion.Kaladesh : CardSetType get() = _Kaladesh
val CardSetTypes.Companion.Khans_of_Tarkir : CardSetType get() = _Khans_of_Tarkir
val CardSetTypes.Companion.Limited_Edition_Alpha : CardSetType get() = _Limited_Edition_Alpha
val CardSetTypes.Companion.Limited_Edition_Beta : CardSetType get() = _Limited_Edition_Beta
val CardSetTypes.Companion.Legends : CardSetType get() = _Legends
val CardSetTypes.Companion.Legions : CardSetType get() = _Legions
val CardSetTypes.Companion.Lorwyn : CardSetType get() = _Lorwyn
val CardSetTypes.Companion.Magic_2010 : CardSetType get() = _Magic_2010
val CardSetTypes.Companion.Magic_2011 : CardSetType get() = _Magic_2011
val CardSetTypes.Companion.Magic_2012 : CardSetType get() = _Magic_2012
val CardSetTypes.Companion.Magic_2013 : CardSetType get() = _Magic_2013
val CardSetTypes.Companion.Magic_2014 : CardSetType get() = _Magic_2014
val CardSetTypes.Companion.Magic_2015 : CardSetType get() = _Magic_2015
val CardSetTypes.Companion.Core_Set_2019 : CardSetType get() = _Core_Set_2019
val CardSetTypes.Companion.Core_Set_2020 : CardSetType get() = _Core_Set_2020
val CardSetTypes.Companion.Core_Set_2021 : CardSetType get() = _Core_Set_2021
val CardSetTypes.Companion.Mirrodin_Besieged : CardSetType get() = _Mirrodin_Besieged
val CardSetTypes.Companion.Mirage : CardSetType get() = _Mirage
val CardSetTypes.Companion.Mercadian_Masques : CardSetType get() = _Mercadian_Masques
val CardSetTypes.Companion.Morningtide : CardSetType get() = _Morningtide
val CardSetTypes.Companion.Mirrodin : CardSetType get() = _Mirrodin
val CardSetTypes.Companion.Nemesis : CardSetType get() = _Nemesis
val CardSetTypes.Companion.New_Phyrexia : CardSetType get() = _New_Phyrexia
val CardSetTypes.Companion.Odyssey : CardSetType get() = _Odyssey
val CardSetTypes.Companion.Oath_of_the_Gatewatch : CardSetType get() = _Oath_of_the_Gatewatch
val CardSetTypes.Companion.Onslaught : CardSetType get() = _Onslaught
val CardSetTypes.Companion.Magic_Origins : CardSetType get() = _Magic_Origins
val CardSetTypes.Companion.Prophecy : CardSetType get() = _Prophecy
val CardSetTypes.Companion.Planar_Chaos : CardSetType get() = _Planar_Chaos
val CardSetTypes.Companion.Planeshift : CardSetType get() = _Planeshift
val CardSetTypes.Companion.Ravnica_City_of_Guilds : CardSetType get() = _Ravnica_City_of_Guilds
val CardSetTypes.Companion.Rivals_of_Ixalan : CardSetType get() = _Rivals_of_Ixalan
val CardSetTypes.Companion.Ravnica_Allegiance : CardSetType get() = _Ravnica_Allegiance
val CardSetTypes.Companion.Rise_of_the_Eldrazi : CardSetType get() = _Rise_of_the_Eldrazi
val CardSetTypes.Companion.Return_to_Ravnica : CardSetType get() = _Return_to_Ravnica
val CardSetTypes.Companion.Scourge : CardSetType get() = _Scourge
val CardSetTypes.Companion.Shadowmoor : CardSetType get() = _Shadowmoor
val CardSetTypes.Companion.Shadows_over_Innistrad : CardSetType get() = _Shadows_over_Innistrad
val CardSetTypes.Companion.Saviors_of_Kamigawa : CardSetType get() = _Saviors_of_Kamigawa
val CardSetTypes.Companion.Scars_of_Mirrodin : CardSetType get() = _Scars_of_Mirrodin
val CardSetTypes.Companion.Stronghold : CardSetType get() = _Stronghold
val CardSetTypes.Companion.Summer_Magic__Edgar : CardSetType get() = _Summer_Magic__Edgar
val CardSetTypes.Companion.Theros_Beyond_Death : CardSetType get() = _Theros_Beyond_Death
val CardSetTypes.Companion.Theros : CardSetType get() = _Theros
val CardSetTypes.Companion.Tempest : CardSetType get() = _Tempest
val CardSetTypes.Companion.Torment : CardSetType get() = _Torment
val CardSetTypes.Companion.Time_Spiral_Timeshifted : CardSetType get() = _Time_Spiral_Timeshifted
val CardSetTypes.Companion.Time_Spiral : CardSetType get() = _Time_Spiral
val CardSetTypes.Companion.Urzas_Destiny : CardSetType get() = _Urzas_Destiny
val CardSetTypes.Companion.Urzas_Legacy : CardSetType get() = _Urzas_Legacy
val CardSetTypes.Companion.Urzas_Saga : CardSetType get() = _Urzas_Saga
val CardSetTypes.Companion.Visions : CardSetType get() = _Visions
val CardSetTypes.Companion.War_of_the_Spark : CardSetType get() = _War_of_the_Spark
val CardSetTypes.Companion.Weatherlight : CardSetType get() = _Weatherlight
val CardSetTypes.Companion.Worldwake : CardSetType get() = _Worldwake
val CardSetTypes.Companion.Ixalan : CardSetType get() = _Ixalan
val CardSetTypes.Companion.Zendikar : CardSetType get() = _Zendikar
val CardSetTypes.Companion.Zendikar_Rising : CardSetType get() = _Zendikar_Rising

//internal val _initCardSets = true